name: bd-trabalho-1-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - psycopg2=2.9.10
  - psycopg2-binary=2.9.10
  - rich=14.0.0
  - pip:
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
