CREATE DATABASE "bd_catalogo_vagas";

-- Tabela de Pessoa
CREATE TABLE PESSOA (
	CPF CHAR(11) PRIMARY KEY,
	MATRICULA VARCHAR(15) UNIQUE NOT NULL,
	NOME VARCHAR(45) NOT NULL,
	EMAIL VARCHAR(45) NOT NULL,
	CEP_END CHAR(8) NOT NULL,
	COMPLEMENTO_END VARCHAR(30) NOT NULL,
	NUMERO_END VARCHAR(10) NOT NULL
);

-- Tabela de Departamento (Professor)
CREATE TABLE DEPARTAMENTO (
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(45) NOT NULL
);

-- Tabela de Curso 
CREATE TABLE CURSO(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
);

-- Tabela de Aluno (Especialização)
CREATE TABLE ALUNO (
	CPF CHAR(11) PRIMARY KEY,
	URL_LATTES VARCHAR(50),
	SEMESTRE INTEGER NOT NULL,
	ID_CURSO INTEGER NOT NULL,
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID) ON DELETE RESTRICT,
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF) ON DELETE CASCADE
);

-- Tabela de Professor (Especialização)
CREATE TABLE PROFESSOR (
	CPF CHAR(11) PRIMARY KEY,
	AREA_PESQUISA VARCHAR(50),
	ID_DEPARTAMENTO INTEGER NOT NULL,
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF) ON DELETE CASCADE,
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID) ON DELETE RESTRICT
);

-- Tabela de Relacionamento: Telefone-Pessoa
CREATE TABLE TELEFONE_PESSOAL (
	CPF CHAR(11),
	NUMERO CHAR(11),
	PRIMARY KEY (CPF, NUMERO),
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF) ON DELETE CASCADE
);

-- Tabela de Empresa
CREATE TABLE EMPRESA (
	CNPJ CHAR(14) PRIMARY KEY,
	SITE_EMP VARCHAR(50),
	RAZAO_SOCIAL VARCHAR(50),
	RAMO_ATIVIDADE VARCHAR(50),
	NOME_FANTASIA VARCHAR(50),
	EMAIL VARCHAR(45) UNIQUE NOT NULL,
	CEP_END CHAR(8) NOT NULL,
	COMPLEMENTO_END VARCHAR(30) NOT NULL,
	NUMERO_END VARCHAR(10) NOT NULL
);

-- Tabela de Relacionamento: Telefone-Empresa
CREATE TABLE TELEFONE_EMPRESARIAL (
	CNPJ CHAR(14),
	NUMERO CHAR(11),
	PRIMARY KEY (CNPJ, NUMERO),
	FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ) ON DELETE CASCADE
);

-- Tabela de Tipo (Vaga)
CREATE TABLE TIPO (
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(45) NOT NULL
);

-- Tabela de Vaga
CREATE TABLE VAGA (
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(255),
	DATA_PUBLICACAO DATE NOT NULL,
	DATA_FIM DATE,
	TITULO VARCHAR(65) NOT NULL,
	CARGA_HORARIA INTEGER NOT NULL,
	CNPJ CHAR(14),
	CPF CHAR(11),
	ID_TIPO INTEGER NOT NULL,
	FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ) ON DELETE CASCADE,
	FOREIGN KEY (CPF) REFERENCES PROFESSOR (CPF) ON DELETE CASCADE,
	FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID) ON DELETE RESTRICT
);

-- Tabela de Área de Interesse
CREATE TABLE AREA_DE_INTERESSE (
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(45) NOT NULL
);

-- Tabela de Relacionamento: Vaga-AreaInteresse
CREATE TABLE AREA_VAGA (
	ID_VAGA INTEGER,
	ID_INTERESSE INTEGER,
	PRIMARY KEY (ID_VAGA, ID_INTERESSE),
	FOREIGN KEY (ID_VAGA) REFERENCES VAGA (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_INTERESSE) REFERENCES AREA_DE_INTERESSE (ID) ON DELETE CASCADE
);

-- Tabela de Relacionamento: Aluno-AreaInteresse
CREATE TABLE ALUNO_INTERESSE (
	CPF CHAR(11),
	ID_INTERESSE INTEGER,
	PRIMARY KEY (CPF, ID_INTERESSE),
	FOREIGN KEY (CPF) REFERENCES ALUNO (CPF) ON DELETE CASCADE,
	FOREIGN KEY (ID_INTERESSE) REFERENCES AREA_DE_INTERESSE (ID) ON DELETE CASCADE
);

-- Tabela de Candidatura (Entidade Fraca)
CREATE TABLE CANDIDATURA (
	CPF CHAR(11),
	ID_VAGA INTEGER,
	STATUS_CANDIDATURA VARCHAR(15) NOT NULL,
	DT_CANDIDATURA DATE NOT NULL,
	ARQUIVO_CURRICULO BYTEA,
	PRIMARY KEY (CPF, ID_VAGA),
	FOREIGN KEY (CPF) REFERENCES ALUNO (CPF) ON DELETE CASCADE,
	FOREIGN KEY (ID_VAGA) REFERENCES VAGA (ID) ON DELETE CASCADE
);
