CREATE DATABASE "bd-trabalho-1";

-- Tabela de Endereco
CREATE TABLE ENDERECO (
	ID SERIAL PRIMARY KEY,
	ESTADO VARCHAR(25),
	CIDADE VARCHAR(25),
	CEP VARCHAR(8),
	BAIRRO VARCHAR(25),
	COMPLEMENTO VARCHAR(30),
	NUMERO VARCHAR(10)
);

-- Tabela de  Pessoa
CREATE TABLE PESSOA (
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(45),
	EMAIL VARCHAR(45),
	ID_ENDERECO INTEGER,
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);

-- Tabela de Departamento (Professor)
CREATE TABLE DEPARTAMENTO (
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(45)
);

-- Tabela de Aluno (Especialização)
CREATE TABLE ALUNO (
	CPF VARCHAR(11) PRIMARY KEY,
	MATRICULA VARCHAR(10) UNIQUE,
	URL_LATTES VARCHAR(50),
	SEMESTRE INTEGER,
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF)
);

-- Tabela de  Professor (Especialização)
CREATE TABLE PROFESSOR (
	CPF VARCHAR(11) PRIMARY KEY,
	MATRICULA VARCHAR(15) UNIQUE,
	AREA_PESQUISA VARCHAR(50),
	ID_DEPARTAMENTO INTEGER,
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF),
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID)
);

-- Tabela de Relacionamento: Telefone-Pessoa
CREATE TABLE TELEFONE_PESSOAL (
	CPF VARCHAR(11),
	NUMERO VARCHAR(15),
	PRIMARY KEY (CPF, NUMERO),
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF)
);

-- Tabela de Empresa
CREATE TABLE EMPRESA (
	CNPJ VARCHAR(14) PRIMARY KEY,
	SITE VARCHAR(50),
	RAZAO_SOCIAL VARCHAR(50),
	RAMO_ATIVIDADE VARCHAR(50),
	NOME_FANTASIA VARCHAR(50),
	EMAIL VARCHAR(45) UNIQUE,
	ID_ENDERECO INTEGER,
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);

-- Tabela de Relacionamento: Telefone-Empresa
CREATE TABLE TELEFONE_EMPRESARIAL (
	CNPJ VARCHAR(14),
	NUMERO VARCHAR(15),
	PRIMARY KEY (CNPJ, NUMERO),
	FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ)
);

-- Tabela de Tipo (Vaga)
CREATE TABLE TIPO (
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(45)
);

-- Tabela de Vaga
CREATE TABLE VAGA (
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(255),
	DATA_PUBLICACAO DATE,
	DATA_FIM DATE,
	TITULO VARCHAR(255),
	CARGA_HORARIA INTEGER,
	CNPJ VARCHAR(14),
	CPF VARCHAR(11),
	ID_TIPO INTEGER,
	FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ),
	FOREIGN KEY (CPF) REFERENCES PROFESSOR (CPF),
	FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID)
);

-- Tabela de Area de Interesse
CREATE TABLE AREA_DE_INTERESSE (
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(45)
);

-- Tabela de Relacionamento: Vaga-AreaInteresse
CREATE TABLE AREA_VAGA (
	ID_VAGA INTEGER,
	ID_INTERESSE INTEGER,
	PRIMARY KEY (ID_VAGA, ID_INTERESSE),
	FOREIGN KEY (ID_VAGA) REFERENCES VAGA (ID),
	FOREIGN KEY (ID_INTERESSE) REFERENCES AREA_DE_INTERESSE (ID)
);

-- Tabela de Relacionamento: Aluno-AreaInteresse
CREATE TABLE ALUNO_INTERESSE (
	CPF VARCHAR(11),
	ID_INTERESSE INTEGER,
	PRIMARY KEY (CPF, ID_INTERESSE),
	FOREIGN KEY (CPF) REFERENCES ALUNO (CPF),
	FOREIGN KEY (ID_INTERESSE) REFERENCES AREA_DE_INTERESSE (ID)
);

-- Tabela de Candidatura (Entidade Fraca)
CREATE TABLE CANDIDATURA (
	CPF VARCHAR(11),
	ID_VAGA INTEGER,
	STATUS VARCHAR(15),
	DT_CANDIDATURA DATE,
	ARQUIVO_CURRICULO BYTEA,
	PRIMARY KEY (CPF, ID_VAGA),
	FOREIGN KEY (CPF) REFERENCES ALUNO (CPF),
	FOREIGN KEY (ID_VAGA) REFERENCES VAGA (ID)
);
