CREATE DATABASE "bd-catalogo-vagas";

-- Tabela de Endereco
CREATE TABLE ENDERECO (
	ID SERIAL PRIMARY KEY,
	ESTADO VARCHAR(25) NOT NULL,
	CIDADE VARCHAR(25) NOT NULL,
	CEP CHAR(8) NOT NULL,
	BAIRRO VARCHAR(25) NOT NULL,
	COMPLEMENTO VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL
);

-- Tabela de Pessoa
CREATE TABLE PESSOA (
	CPF CHAR(11) PRIMARY KEY,
	MATRICULA VARCHAR(15) UNIQUE NOT NULL,
	NOME VARCHAR(45) NOT NULL,
	EMAIL VARCHAR(45) NOT NULL,
	ID_ENDERECO INTEGER NOT NULL,
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);

-- Tabela de Departamento (Professor)
CREATE TABLE DEPARTAMENTO (
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(45) NOT NULL
);

-- Tabela de Curso 
CREATE TABLE DEPARTAMENTO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
);

-- Tabela de Aluno (Especialização)
CREATE TABLE ALUNO (
	CPF CHAR(11) PRIMARY KEY,
	URL_LATTES VARCHAR(50),
	SEMESTRE INTEGER NOT NULL,
	ID_CURSO INTEGER NOT NULL,
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID)
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF)
);

-- Tabela de Professor (Especialização)
CREATE TABLE PROFESSOR (
	CPF CHAR(11) PRIMARY KEY,
	AREA_PESQUISA VARCHAR(50),
	ID_DEPARTAMENTO INTEGER NOT NULL,
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF),
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID)
);

-- Tabela de Relacionamento: Telefone-Pessoa
CREATE TABLE TELEFONE_PESSOAL (
	CPF CHAR(11),
	NUMERO CHAR(11),
	PRIMARY KEY (CPF, NUMERO),
	FOREIGN KEY (CPF) REFERENCES PESSOA (CPF)
);

-- Tabela de Empresa
CREATE TABLE EMPRESA (
	CNPJ CHAR(14) PRIMARY KEY,
	SITE_EMP VARCHAR(50),
	RAZAO_SOCIAL VARCHAR(50),
	RAMO_ATIVIDADE VARCHAR(50),
	NOME_FANTASIA VARCHAR(50),
	EMAIL VARCHAR(45) UNIQUE NOT NULL,
	ID_ENDERECO INTEGER NOT NULL,
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);

-- Tabela de Relacionamento: Telefone-Empresa
CREATE TABLE TELEFONE_EMPRESARIAL (
	CNPJ CHAR(14),
	NUMERO CHAR(11),
	PRIMARY KEY (CNPJ, NUMERO),
	FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ)
);

-- Tabela de Tipo (Vaga)
CREATE TABLE TIPO (
	ID SERIAL PRIMARY KEY NOT NULL, 
	NOME VARCHAR(45) NOT NULL
);

-- Tabela de Vaga
CREATE TABLE VAGA (
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(255),
	DATA_PUBLICACAO DATE,
	DATA_FIM DATE,
	TITULO VARCHAR(255),
	CARGA_HORARIA INTEGER,
	CNPJ CHAR(14),
	CPF CHAR(11),
	ID_TIPO INTEGER,
	FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ),
	FOREIGN KEY (CPF) REFERENCES PROFESSOR (CPF),
	FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID)
);

-- Tabela de Área de Interesse
CREATE TABLE AREA_DE_INTERESSE (
	ID SERIAL PRIMARY KEY NOT NULL, 
	NOME VARCHAR(45) NOT NULL
);

-- Tabela de Relacionamento: Vaga-AreaInteresse
CREATE TABLE AREA_VAGA (
	ID_VAGA INTEGER NOT NULL,
	ID_INTERESSE INTEGER NOT NULL,
	PRIMARY KEY (ID_VAGA, ID_INTERESSE),
	FOREIGN KEY (ID_VAGA) REFERENCES VAGA (ID),
	FOREIGN KEY (ID_INTERESSE) REFERENCES AREA_DE_INTERESSE (ID)
);

-- Tabela de Relacionamento: Aluno-AreaInteresse
CREATE TABLE ALUNO_INTERESSE (
	CPF CHAR(11),
	ID_INTERESSE INTEGER,
	PRIMARY KEY (CPF, ID_INTERESSE),
	FOREIGN KEY (CPF) REFERENCES ALUNO (CPF),
	FOREIGN KEY (ID_INTERESSE) REFERENCES AREA_DE_INTERESSE (ID)
);

-- Tabela de Candidatura (Entidade Fraca)
CREATE TABLE CANDIDATURA (
	CPF CHAR(11),
	ID_VAGA INTEGER,
	STATUS_CANDIDATURA VARCHAR(15) NOT NULL,
	DT_CANDIDATURA DATE NOT NULL,
	ARQUIVO_CURRICULO BYTEA,
	PRIMARY KEY (CPF, ID_VAGA),
	FOREIGN KEY (CPF) REFERENCES ALUNO (CPF),
	FOREIGN KEY (ID_VAGA) REFERENCES VAGA (ID)
);
